version: '3.4'

services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_USER: docker
      MYSQL_PASSWORD: defaultpassword
      MYSQL_DATABASE: rest_with_spring_boot
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - gadiel-network

  rest-with-spring-boot:
    image: gadielbarros/rest-with-spring-boot
    restart: always
    build: ./rest-with-spring-boot
    working_dir: /rest-with-spring-boot
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: strongpassword
    command: mvn spring-boot:run
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - gadiel-network

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - gadiel-network

volumes:
  portainer_data:

networks:
  gadiel-network:
    driver: bridge